config/routes.rb
Pushfish::Application.routes.draw do
  resources :anglers

end

app/models/angler.rb
class Angler < ActiveRecord::Base
  has_many :fishes
  attr_accessible :boat_num, :name
end

app/controllers/anglers_controller.rb
class AnglersController < ApplicationController
  # GET /anglers
  # GET /anglers.json
  def index
    @anglers = Angler.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @anglers }
    end
  end

  # GET /anglers/1
  # GET /anglers/1.json
  def show
    @angler = Angler.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @angler }
    end
  end

  # GET /anglers/new
  # GET /anglers/new.json
  def new
    @angler = Angler.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @angler }
    end
  end

  # GET /anglers/1/edit
  def edit
    @angler = Angler.find(params[:id])
  end

  # POST /anglers
  # POST /anglers.json
  def create
    @angler = Angler.new(params[:angler])

    respond_to do |format|
      if @angler.save
        format.html { redirect_to @angler, notice: 'Angler was successfully created.' }
        format.json { render json: @angler, status: :created, location: @angler }
      else
        format.html { render action: "new" }
        format.json { render json: @angler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /anglers/1
  # PUT /anglers/1.json
  def update
    @angler = Angler.find(params[:id])

    respond_to do |format|
      if @angler.update_attributes(params[:angler])
        format.html { redirect_to @angler, notice: 'Angler was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @angler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /anglers/1
  # DELETE /anglers/1.json
  def destroy
    @angler = Angler.find(params[:id])
    @angler.destroy

    respond_to do |format|
      format.html { redirect_to anglers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/anglers_helper.rb
module AnglersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/anglers/_form.html.erb
<%= form_for(@angler) do |f| %>
  <% if @angler.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@angler.errors.count, "error") %> prohibited this angler from being saved:</h2>

      <ul>
      <% @angler.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :boat_num %><br />
    <%= f.number_field :boat_num %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/anglers/edit.html.erb
<h1>Editing angler</h1>

<%= render 'form' %>

<%= link_to 'Show', @angler %> |
<%= link_to 'Back', anglers_path %>

app/views/anglers/index.html.erb
<h1>Listing anglers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Boat num</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @anglers.each do |angler| %>
  <tr>
    <td><%= angler.name %></td>
    <td><%= angler.boat_num %></td>
    <td><%= link_to 'Show', angler %></td>
    <td><%= link_to 'Edit', edit_angler_path(angler) %></td>
    <td><%= link_to 'Destroy', angler, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Angler', new_angler_path %>

app/views/anglers/new.html.erb
<h1>New angler</h1>

<%= render 'form' %>

<%= link_to 'Back', anglers_path %>

app/views/anglers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @angler.name %>
</p>

<p>
  <b>Boat num:</b>
  <%= @angler.boat_num %>
</p>


<%= link_to 'Edit', edit_angler_path(@angler) %> |
<%= link_to 'Back', anglers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pushfish</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>